Training started...
Error executing job with overrides: []                                                                                                                                              
[2025-04-10 11:35:55,337][__main__][INFO] - Train Epoch: 0 [0/51 (0%)]	Loss: 1.371976
Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 277, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 102, in train
    output = model(features)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 341, in forward
    return self.naim(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 321, in forward
    embeddings = encoder_layer(embeddings, mask=masks, mask2=masks2)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 221, in forward
    x = x + self.attn(inp_x, inp_x, inp_x, mask=mask, mask2=mask2)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 152, in forward
    y, attn_scores = self._scaled_dot_product_attention(q, k, v, attn_mask=mask, attn_mask_2=mask2)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 178, in _scaled_dot_product_attention
    q = q / math.sqrt(E)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
